version: "3.9"
services:
  mysql:
    image: 'mysql:latest'
    container_name: mysql_flyway_database
    environment:
      - 'MYSQL_ROOT_PASSWORD=12345'
      - 'MYSQL_DATABASE=flyway_database'
      - 'MYSQL_USER=darkus'
      - 'MYSQL_PASSWORD=1999'
    ports:
      - "3307:3306"